spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  jpa:
    hibernate:
#      use-new-id-generator-mappings: false
#      ddl-auto: create
    show-sql: true
comment.avatar: /images/wo.JPG


